name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM CI
        run: npm ci
      
      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm run test
        env:
          MONGOOSE_TEST_DB: mongodb+srv://developer:ZJPdw6W5yJChaKWy@cluster0.lqquy.mongodb.net/tippy_test?retryWrites=true&w=majority
